# Generated by Django 2.0.5 on 2018-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='items/%Y/%m/%d', verbose_name='Дополнительная фотография'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_main',
            field=models.ImageField(upload_to='items/%Y/%m/%d', verbose_name='Главная фотография'),
        ),
    ]
