# Generated by Django 2.0.5 on 2018-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181009_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/image/not_found.jpg', upload_to='category/%Y/%m', verbose_name='Фотография категории'),
        ),
    ]
