# Generated by Django 2.0.5 on 2018-10-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
