# Generated by Django 2.0.5 on 2018-10-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptions',
            new_name='description',
        ),
    ]
